//export const dynamic = 'force-dynamic';
//export const revalidate = 5;
//export const fetchCache = 'force-no-store';
//import { headers } from 'next/headers';

import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const getData = async () => {
  const response = await fetch('http://localhost:3000/api/source');
  const data = await response.json();

  return data;
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  // const head = headers();
  const data = getData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            height: '15vh',
            backgroundColor: '#2c0303',
            textAlign: 'center',
            fontSize: '40px'
          }}
        >
          Root layout
          <h1>{data}</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
